name: "wave_encoder"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [512, -1, -1]
  },
  {
    name: "skips"
    data_type: TYPE_FP32
    format: FORMAT_NONE
    dims: [ -1, -1, -1, -1 ]  # Variable dimensions due to the skip connections
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [3, -1, -1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]